### ISSUE TITLE
Uncaught RangeError: Offset is outside the bounds of the DataView

### ISSUE THREAD

**Issue by rever96** [whichsteven/UW_Point_Cloud#23]
Hi, im trying running your code and get this error when loading the pointcloud.

![image](https://user-images.githubusercontent.com/19595534/85774114-d5144a00-b71e-11ea-932b-bdc80dddba84.png)

It seems that the loop fall out of bound.

Am I wrong?

**Comment by whichsteven** [comment]
Hi, we upload the point cloud data using `git-lfs`. Please try install git-lfs first and then clone the repository because otherwise the data won’t actually be downloaded.

**Comment by rever96** [comment]
oh, thx for the fast reply.
Yes, the problem was about the data that i didn't downloaded properly, I've tested with a smaller pointcloud and it works (it isn't centered on the map with infopoint, but no problem it's even a data problem)
